#!/bin/bash


########################
## DEFAULT pre-commit ##
########################

# Check if this is the initial commit
if git rev-parse --verify HEAD >/dev/null 2>&1; then
    # Creating a new commit
    against=HEAD
else
    # Initial commit (diff against an empty tree object)
    against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

#######################
### Terraform fmt ####
#######################

# Get all changed .tf files' directories
tf_dir_changed=$(git diff --name-only --diff-filter=ACMRT --cached $against | grep .tf$ | xargs -r -L 1 dirname | sort -u)

# Run terraform fmt on all directories with changes
if command -v terraform version &> /dev/null; then
    echo 'Checking format of Terraform files'
    for dir in $tf_dir_changed; do
        echo "Checking formatting for .tf files in ${dir}"
        terraform fmt -write=false -diff -check "${dir}"
        if [ $? -ne 0 ]; then
            echo "Formatting .tf files in ${dir}"
            terraform fmt "{$dir}"
            git add "${dir}/*.tf"
        fi
    done
else
    echo "[pre-commit hook] Skipping running terraform fmt because terraform was not found"
fi